name: pico-uart-bridge

on:
  - push
  - pull_request

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: pico
            name: Raspberry Pi Pico
          - board: pico2
            name: Raspberry Pi Pico 2
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: |
          sudo apt-get install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: 'Update Submodules'
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: 'Configure'
        run: |
          mkdir -p build
          cmake -B build -DPICO_BOARD=${{ matrix.board }}

      - name: 'Build'
        run: |
          make -C build

      - name: 'Upload binary'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.board }}-uart-bridge.uf2
          path: build/uart_bridge.uf2
          retention-days: 5
